#!/command/with-contenv bash

# create directories
mkdir -p \
  /app \
  /config/{repositories,nginx,log/nginx} \
  /var/cache/cgit

# copy files
[[ ! -f /config/cgitrc ]] && \
  cp /files/cgitrc /config/cgitrc
[[ ! -f /config/nginx/nginx.conf ]] && \
  cp /files/nginx.conf /config/nginx/nginx.conf

# fix permissions
chown -R yaapc:yaapc \
  /app \
  /config \
  /var/cache/cgit
