#!/usr/bin/with-contenv bash

# create directories
mkdir -p \
	/app \
	/config/{repositories,nginx,log/nginx} \
	/var/cache/cgit

# copy files
[[ ! -f /config/cgitrc ]] && \
	cp /files/cgitrc /config/cgitrc
[[ ! -f /config/nginx/nginx.conf ]] && \
	cp /files/nginx.conf /config/nginx/nginx.conf

# clone example repositories
if [[ ! "$(ls -A ${CONFIG_DIR}/repositories/)" ]]; then
	git clone https://github.com/chruth/alpine-cgit.git /config/repositories/alpine-cgit
	git clone https://github.com/chruth/alpine-base.git /config/repositories/alpine-base
fi

# fix permissions
chown -R yaapc:yaapc \
	/app \
	/config \
	/var/cache/cgit